cmake_minimum_required(VERSION 3.20)

# Write snapshots/<SNAPSHOT>.cmake from the current on-disk state of every project.
#
# Expected variables (passed with -D):
#   SNAPSHOT  name of the snapshot (only used for the header comment)
#   MANIFEST  path to the project manifest (one "NAME|SOURCE_DIR" per line)
#   OUTPUT    path of the snapshot file to write

if("${SNAPSHOT}" STREQUAL "")
  message(
    FATAL_ERROR
      "No snapshot name provided. Configure with -DSNAPSHOT=<name> before running save-snapshot."
  )
endif()

if(NOT EXISTS "${MANIFEST}")
  message(FATAL_ERROR "Manifest not found: ${MANIFEST}")
endif()

file(STRINGS "${MANIFEST}" _entries)

string(TIMESTAMP _now UTC)
set(_content
    "# mc-rtc-superbuild source snapshot '${SNAPSHOT}'\n"
    "#\n"
    "# Generated by the save-snapshot target on ${_now}.\n"
    "# Do not edit by hand: regenerate with\n"
    "#   cmake --build <build> --target save-snapshot   (with -DSNAPSHOT=${SNAPSHOT})\n"
    "#\n"
    "# Activate with -DSNAPSHOT=${SNAPSHOT} and apply with the restore-snapshot target.\n"
    "\n"
)
string(JOIN "" _content ${_content})

set(_count 0)
set(_skipped 0)
foreach(_entry ${_entries})
  if("${_entry}" STREQUAL "")
    continue()
  endif()
  string(REPLACE "|" ";" _parts "${_entry}")
  list(GET _parts 0 _name)
  list(GET _parts 1 _src)

  if(NOT EXISTS "${_src}/.git")
    message(STATUS "[SKIP] ${_name}: ${_src} is not a git repository")
    math(EXPR _skipped "${_skipped} + 1")
    continue()
  endif()

  execute_process(
    COMMAND git rev-parse HEAD
    WORKING_DIRECTORY "${_src}"
    OUTPUT_VARIABLE _sha
    OUTPUT_STRIP_TRAILING_WHITESPACE
    RESULT_VARIABLE _sha_err
  )
  if(_sha_err OR "${_sha}" STREQUAL "")
    message(STATUS "[SKIP] ${_name}: cannot resolve HEAD")
    math(EXPR _skipped "${_skipped} + 1")
    continue()
  endif()

  execute_process(
    COMMAND git remote get-url origin
    WORKING_DIRECTORY "${_src}"
    OUTPUT_VARIABLE _url
    OUTPUT_STRIP_TRAILING_WHITESPACE
    RESULT_VARIABLE _url_err
  )
  if(_url_err)
    set(_url "")
  endif()

  # Warn (but still record) when the working tree is dirty: the snapshot will capture
  # the committed HEAD, not the uncommitted changes.
  execute_process(
    COMMAND git status --porcelain --untracked-files=no
    WORKING_DIRECTORY "${_src}"
    OUTPUT_VARIABLE _dirty
    OUTPUT_STRIP_TRAILING_WHITESPACE
  )
  if(NOT "${_dirty}" STREQUAL "")
    message(
      WARNING
        "${_name} has uncommitted changes; snapshot records committed HEAD ${_sha} only."
    )
  endif()

  string(APPEND _content "set(MC_RTC_SUPERBUILD_SNAPSHOT_${_name}_GIT_TAG ${_sha})\n")
  if(NOT "${_url}" STREQUAL "")
    string(APPEND _content "set(MC_RTC_SUPERBUILD_SNAPSHOT_${_name}_REMOTE ${_url})\n")
  endif()
  math(EXPR _count "${_count} + 1")
endforeach()

get_filename_component(_outdir "${OUTPUT}" DIRECTORY)
file(MAKE_DIRECTORY "${_outdir}")
file(WRITE "${OUTPUT}" "${_content}")

message(STATUS "Wrote snapshot '${SNAPSHOT}' with ${_count} project(s) to ${OUTPUT}")
if(_skipped GREATER 0)
  message(STATUS "${_skipped} project(s) were skipped (not cloned / no HEAD)")
endif()
