include(${CMAKE_CURRENT_LIST_DIR}/tasks/minimum_jerk_task.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/interfaces/mc_mujoco.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/plugins/mc_ros_force_sensor.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/plugins/mc_residual_estimation.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/plugins/mc_joystick_plugin.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/plugins/mc_ros_force_sensor.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/controllers/force_sensor_calibration_controller.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/controllers/monodzukuri.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/controllers/torque_test.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/controllers/humanoid_explicit_compliance.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/controllers/explicit_compliance_controller.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/controllers/box-carrying-demo.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/controllers/ismpc_walking.cmake)
# include(${CMAKE_CURRENT_LIST_DIR}/controllers/ismpc_walking_torque.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/controllers/jst-mirai-tactile-demo.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/controllers/mc_logistic_controller.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/controllers/collaborative_peg_in_hole_controller.cmake)
