include(${CMAKE_CURRENT_LIST_DIR}/tasks/minimum_jerk_task.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/interfaces/mc_kortex.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/interfaces/mc_mujoco.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/plugins/mc_joystick_plugin.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/plugins/mc_residual_estimation.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/plugins/mc_passivity_torque_feedback.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/plugins/mc_ros_force_sensor.cmake)
# include(${CMAKE_CURRENT_LIST_DIR}/controllers/phri_hl_controller.cmake)
# include(${CMAKE_CURRENT_LIST_DIR}/catkin_projects/phri_hl_exp_ros_msg.cmake)
# include(${CMAKE_CURRENT_LIST_DIR}/gui/mc_rtc-magnum.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/controllers/ral_exp_external_forces.cmake)
# include(${CMAKE_CURRENT_LIST_DIR}/controllers/ral_exp_hierarchical_external_forces.cmake)
# include(${CMAKE_CURRENT_LIST_DIR}/controllers/phri_controller.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/controllers/minimum_jerk_controller.cmake)
# include(${CMAKE_CURRENT_LIST_DIR}/catkin_projects/bota_driver.cmake)
# include(${CMAKE_CURRENT_LIST_DIR}/environments/fitts_game.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/controllers/fitts_law_controller.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/controllers/user_preference_controller.cmake)
# include(${CMAKE_CURRENT_LIST_DIR}/controllers/mc_force_sensor_calibration_controller.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/controllers/monodzukuri_demo.cmake)
# include(${CMAKE_CURRENT_LIST_DIR}/controllers/contact_torque_controller.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/controllers/turing_controller.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/controllers/ijrr_vel_drop_controller.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/controllers/torque_tracking_controller.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/controllers/humanoid_explicit_compliance.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/controllers/tasks_torque_test.cmake)
